### ISSUE TITLE
Update the version

### ISSUE THREAD

**Issue by somenxavier** [jgraichen/debian-isso#11]
Hi,

Please update the version of debian-isso. The last release is [0.9.10](https://github.com/jgraichen/debian-isso/releases) but now there is [0.10.1](https://github.com/posativ/isso/blob/master/CHANGES.rst)

**Comment by JocelynDelalande** [comment]
Will sure give a look at it if I get some time anytime soon. Meanwhile, il you have skills will & time, feel free to submit a PR @somenxavier :)

**Comment by somenxavier** [comment]
I have no these skills. I'm just a proactive user ;-)

**Comment by JocelynDelalande** [comment]
Xavier <notifications@github.com> wrote:
> I have no these skills. I'm just a proactive user ;-)

No prob, thanks for reporting anyway :-), I'll get a look at it.

Jocelyn

**Comment by somenxavier** [comment]
Now 0.10.4. How can I help to fix this bug? How can you update the version?

**Comment by somenxavier** [comment]
Thanks, a lot

**Comment by JocelynDelalande** [comment]
@somenxavier  np :-) Please let me know if it works well, I uploaded it to https://packages.crapouillou.net also

**Comment by somenxavier** [comment]
What this means? Can we add `https://packages.crapouillou.net/` into `sources.list`? How? In your [README](https://github.com/jgraichen/debian-isso/blob/master/debian/README.md) you don't mention it.

**Comment by somenxavier** [comment]
I received this:
```
# dpkg -i isso_0.10.4-1_all.deb 
(Reading database ... 43986 files and directories currently installed.)
Preparing to unpack isso_0.10.4-1_all.deb ...
Unpacking isso (0.10.4-1) over (0.9.10-1) ...
Setting up isso (0.10.4-1) ...
insserv: warning: current start runlevel(s) (empty) of script `isso' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `isso' overrides LSB defaults (0 1 6).
Processing triggers for systemd (215-17+deb8u4) ...
root@deimos:/home/xan# 
```

**Comment by somenxavier** [comment]
It works

**Comment by JocelynDelalande** [comment]
Xavier <notifications@github.com> wrote:
> What this means? Can we add `https://packages.crapouillou.net/`

See documentation on : https://packages.crapouillou.net/

> into `sources.list`? How? In your
> [README](https://github.com/jgraichen/debian-isso/blob/master/debian/README.md)
> you don't mention it.

Good point, now it I do :-)
