### ISSUE TITLE
Tested 0.10.4 version in Ubuntu 16.04

### ISSUE THREAD

**Issue by cryptofuture** [jgraichen/debian-isso#12]
You miss 
```sh
python-configparser,
python-ipaddr,
python-werkzeug (>= 0.9~)
```
Build-Depends in control file. And maybe (not sure) `dh-python` package too, (this package only to remove warning).  [Build log](https://launchpadlibrarian.net/262773506/buildlog_ubuntu-xenial-amd64.isso_0.10.4-ppa18~xenial_BUILDING.txt.gz).
But really bad thing is, I was unable to make isso work at all. Is it suppose to reply to `curl -i 127.0.0.1:bindport? (no reply in my case, really strange, and always timeout from upstream)
More above both 0.9.9-1 (default version in Ubuntu repository, not sure you maintain it) and your  0.10.4 version always runs on 8000 port. I think systemd just ignores settings from /etc/default.
Location settings I tried, want to run isso in /comments folder.
```
location /comments {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Script-Name /comments;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://127.0.0.1:8000;
        }
```
```
location /comments {
                proxy_pass http://127.0.0.1:8000;
        }
```
```
location /comments {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://127.0.0.1:8000;
        }
```
P.S.: I can take Ubuntu PPA maintain or I can remove it, if you want take Debian-based dists maintaining under: https://packages.crapouillou.net (currently down), only found you repo pgp key [here](https://code.crapouillou.net/jocelyn/ansible-roles/blob/9e55c79d62ab6a94bd983833b87630eb1610b7f2/isso/tasks/main.yml).
Don't want to spam isso with this issue. Well, probably missing depends and trouble with port ignoring from etc/default/isso is package issue here. But seems like isso not working as intended at all, since I can even curl it.  Any ideas @posativ . I'm pretty sure isso service starting ok, since I see gunicorn on 8000 port. (both INPUT/OUTPUT accept on lo in iptables). And well I have another things running locally without any problem.

**Comment by JocelynDelalande** [comment]
Thanks for reporting :)

Which ppa are you talking about ?

 Could you provide a patch that would make it ok for you on ubuntu ? (it's currently only built for Debian).

**Comment by cryptofuture** [comment]
Can you create new branch for ubuntu? (better totally empty for now) I decided to ignore older then current LTS versions, so it will be pure systemd package. I'm done with posativ setup myself, and I think I'll be able to share  package today, or (in bad case) tomorrow. But I'll make posativ as git submodule, what you think about that?

**Comment by cryptofuture** [comment]
Ready:
https://github.com/cryptofuture/isso-ubuntu

**Comment by JocelynDelalande** [comment]
@cryptofuture sorry for the huge lag…

Maybe the simplest option is that you maintain packages for ubuntu LTS and I maintain packages for Debian ? Separate github repositories and separate deb hosting.

For package hosting, I see two reasons why It's better if you manage them yourself on a ppa :

- It's the simplest way to add 3rd-party repositories for ubuntu
- I won't be able to provide any support/test for ubuntu packages (as I don't use ubuntu).

What do you think ?

**Comment by cryptofuture** [comment]
>What do you think ?
Good for me. I already have shitload of ppa to support, one extra will not make a change anyway.

**Comment by JocelynDelalande** [comment]
Deal set !
