### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by JocelynDelalande** [jgraichen/debian-isso#13]
from #12

> python-configparser,
> python-ipaddr,
> python-werkzeug (>= 0.9~)

**Comment by somenxavier** [comment]
Put in README

**Comment by JocelynDelalande** [comment]
@somenxavier Why that ?

**Comment by JocelynDelalande** [comment]
fixed in f81b6b86c3b864ed025d76b886b09d8794a1f4e7

**Comment by somenxavier** [comment]
@JocelynDelalande It's useful to have the dependencies documented.

**Comment by JocelynDelalande** [comment]
> @JocelynDelalande It's useful to have the dependencies documented.

My take on this :  they already are in debian/control, so I won't list them in another place (the risk is to later forget to update requirements in README too). 

Moreover this repo is not an install guide but  package data.
