### ISSUE TITLE
Need to upgrade

### ISSUE THREAD

**Issue by somenxavier** [jgraichen/debian-isso#14]
As [you see](https://github.com/posativ/isso/releases) there is 0.10.6 release available. Please upgrade your repo because you have only version 0.10.4. Thanks

**Comment by JocelynDelalande** [comment]
@somenxavier thanks for noticing, I started working on it, still some little things to figure out before releasing.

**Comment by somenxavier** [comment]
@JocelynDelalande Thanks a lot. I could be the sneaker of releases ;-)
