### ISSUE TITLE
ImportError: No module named sanitizer

### ISSUE THREAD

**Issue by tunmsk** [jgraichen/debian-isso#16]
Hello sir , 
I built the debian package on a debian 9 stretch : there were some dependecies to install , everything was ok until starting the service and this is the error 
isso.service - lightweight Disqus alternative
   Loaded: loaded (/lib/systemd/system/isso.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-09-05 21:34:08 CEST; 549ms ago
  Process: 21326 ExecStart=/usr/bin/gunicorn --log-file /var/log/isso.log --preload isso.run (code=exited, status=1/FAILURE)
 Main PID: 21326 (code=exited, status=1/FAILURE)

Sep 05 21:34:08  gunicorn[21326]:   File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 384, in import_app
Sep 05 21:34:08 gunicorn[21326]:     __import__(module)
Sep 05 21:34:08 gunicorn[21326]:   File "/usr/lib/python2.7/dist-packages/isso/__init__.py", line 71, in <module>
Sep 05 21:34:08  gunicorn[21326]:     from isso.utils import http, JSONRequest, html, hash
Sep 05 21:34:08  gunicorn[21326]:   File "/usr/lib/python2.7/dist-packages/isso/utils/html.py", line 16, in <module>
Sep 05 21:34:08  gunicorn[21326]:     from html5lib.sanitizer import HTMLSanitizer
Sep 05 21:34:08  gunicorn[21326]: ImportError: No module named sanitizer
Sep 05 21:34:08  systemd[1]: isso.service: Main process exited, code=exited, status=1/FAILURE
Sep 05 21:34:08  systemd[1]: isso.service: Unit entered failed state.
Sep 05 21:34:08  systemd[1]: isso.service: Failed with result 'exit-code'.

I googled the error and seems like there's some functions removed from the html5lib causing that , I tried resolve it but no success , could you help fix that , thanks

**Comment by somenxavier** [comment]
here the same error.
